[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = "3.12"

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]
